#!/usr/bin/env python3
"""Generate a deterministic docs index from Markdown sources under docs/."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/reference/GENERATED_DOCS_INDEX.md")
IGNORED_DIR_NAMES = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    ".cache",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
}


def _iter_markdown_files(docs_root: Path, output: Path) -> list[Path]:
    if not docs_root.exists():
        return []

    output = output.resolve()
    files: list[Path] = []

    for root, dirnames, filenames in os.walk(docs_root):
        root_path = Path(root)
        dirnames[:] = [name for name in dirnames if name not in IGNORED_DIR_NAMES]

        for filename in filenames:
            if not filename.endswith(".md"):
                continue
            path = root_path / filename
            if path.resolve() == output:
                continue
            files.append(path)

    return sorted(files, key=lambda path: path.relative_to(docs_root).as_posix())


def build_index(root: Path, output: Path) -> str:
    docs_root = root / "docs"
    files = _iter_markdown_files(docs_root, output)

    lines = [
        "# Generated Docs Index",
        "",
        "This file is generated by `scripts/docs/generate_docs_index.py`.",
        "",
    ]

    if not files:
        lines.extend(["_No Markdown docs found._", ""])
        return "\n".join(lines)

    for path in files:
        rel = path.relative_to(docs_root)
        link = os.path.relpath(path, output.parent).replace(os.sep, "/")
        lines.append(f"- [{rel.as_posix()}]({link})")

    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root to scan.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Generated markdown file to write or check.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated file is missing or stale.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    output = output.resolve()
    content = build_index(root, output)

    if args.check:
        try:
            existing = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated docs index: {output}")
            return 1
        if existing != content:
            print(f"stale generated docs index: {output}")
            return 1
        print(f"generated docs index is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"wrote generated docs index: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
