"""Response models for the orchestrator API."""

from typing import Any

from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """Response model for chat endpoint."""

    answer: str = Field(..., description="The final answer")
    turns: int = Field(..., description="Number of orchestration turns used")
    tokens_used: int = Field(default=0, description="Approximate tokens used")
    elapsed_seconds: float = Field(..., description="Total processing time")
    mock_mode: bool = Field(..., description="Whether mock mode was used")
    real_mode: bool = Field(default=False, description="Whether real inference was used")
    cache_stats: dict[str, Any] | None = Field(
        default=None, description="Cache performance statistics (real_mode only)"
    )
    routed_to: str = Field(default="", description="Primary role that handled the request")
    role_history: list[str] = Field(
        default_factory=list, description="Full role chain if escalated"
    )
    routing_strategy: str = Field(
        default="", description="How routing was decided: learned|rules|default"
    )
    mode: str = Field(
        default="", description="Execution mode: direct, react, repl, delegated, or mock"
    )
    tokens_generated: int = Field(default=0, description="Tokens generated by inference backends")
    formalization_applied: bool = Field(
        default=False, description="Whether input formalization was applied"
    )
    tools_used: int = Field(default=0, description="Number of tool invocations during execution")
    tools_called: list[str] = Field(
        default_factory=list, description="Names of tools invoked during execution"
    )
    # Clean timing data from llama.cpp (excludes prompt eval overhead)
    prompt_eval_ms: float = Field(default=0.0, description="Prompt evaluation time in ms")
    generation_ms: float = Field(
        default=0.0, description="Token generation time in ms (excludes prompt eval)"
    )
    predicted_tps: float = Field(
        default=0.0, description="Clean generation-only tokens/second from llama.cpp"
    )
    http_overhead_ms: float = Field(
        default=0.0, description="Server-side overhead: HTTP round-trip minus inference time (ms)"
    )
    # Error signaling (Phase 1b): explicit failure codes instead of silent 200 OK
    error_code: int | None = Field(
        default=None,
        description="Error code if request failed (504=timeout, 502=backend down, None=success)",
    )
    error_detail: str | None = Field(
        default=None, description="Structured error description when error_code is set"
    )


class HealthResponse(BaseModel):
    """Response model for health endpoint."""

    status: str = Field(..., description="Health status: ok | degraded")
    models_loaded: int = Field(default=0, description="Number of healthy backends")
    mock_mode_available: bool = Field(default=True, description="Mock mode availability")
    version: str = Field(default="0.1.0", description="API version")
    backend_health: dict[str, Any] | None = Field(
        default=None,
        description="Per-backend circuit breaker status (URL → state/failure_count/cooldown)",
    )


class GateResultModel(BaseModel):
    """Model for individual gate result."""

    gate_name: str
    passed: bool
    exit_code: int
    elapsed_seconds: float
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class GatesResponse(BaseModel):
    """Response model for gates endpoint."""

    results: list[GateResultModel]
    all_passed: bool
    total_elapsed_seconds: float


class StatsResponse(BaseModel):
    """Response model for stats endpoint."""

    total_requests: int
    total_turns: int
    average_turns_per_request: float
    mock_requests: int
    real_requests: int
