"""Response models for the orchestrator API."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ToolTiming(BaseModel):
    """Per-tool invocation timing record."""

    tool_name: str = Field(..., description="Name of the tool invoked")
    elapsed_ms: float = Field(default=0.0, description="Wall-clock time for this invocation")
    success: bool = Field(default=True, description="Whether the invocation succeeded")
    output_tokens: int = Field(default=0, description="Estimated tokens in tool output (~len/4)")


class DelegationEvent(BaseModel):
    """Record of a delegation that occurred during request processing."""

    from_role: str = Field(..., description="Role that delegated")
    to_role: str = Field(..., description="Role that received delegation")
    task_summary: str = Field(default="", description="What was delegated")
    success: bool | None = Field(
        default=None, description="Whether delegated work succeeded"
    )
    elapsed_ms: float = Field(default=0.0, description="Time spent on delegated work")
    tokens_generated: int = Field(default=0, description="Tokens generated by delegate")


class ChatResponse(BaseModel):
    """Response model for chat endpoint."""

    answer: str = Field(..., description="The final answer")
    turns: int = Field(..., description="Number of orchestration turns used")
    tokens_used: int = Field(default=0, description="Approximate tokens used")
    elapsed_seconds: float = Field(..., description="Total processing time")
    mock_mode: bool = Field(..., description="Whether mock mode was used")
    real_mode: bool = Field(default=False, description="Whether real inference was used")
    cache_stats: dict[str, Any] | None = Field(
        default=None, description="Cache performance statistics (real_mode only)"
    )
    routed_to: str = Field(default="", description="Primary role that handled the request")
    role_history: list[str] = Field(
        default_factory=list, description="Full role chain if escalated"
    )
    routing_strategy: str = Field(
        default="", description="How routing was decided: learned|rules|default"
    )
    mode: str = Field(
        default="", description="Execution mode: direct, react, repl, delegated, or mock"
    )
    tokens_generated: int = Field(default=0, description="Tokens generated by inference backends")
    tool_output_tokens: int = Field(
        default=0,
        description="Estimated tokens produced by tool outputs (~len/4), treating tools as throughput amplifiers",
    )
    formalization_applied: bool = Field(
        default=False, description="Whether input formalization was applied"
    )
    tools_used: int = Field(default=0, description="Number of tool invocations during execution")
    tools_called: list[str] = Field(
        default_factory=list, description="Names of tools invoked during execution"
    )
    tool_timings: list[ToolTiming] = Field(
        default_factory=list,
        description="Per-tool invocation timing (name, elapsed_ms, success)",
    )
    tool_chains: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Grouped chained tool invocations with chain_id/steps/status",
    )
    delegation_events: list[DelegationEvent] = Field(
        default_factory=list,
        description="Structured delegation events during this request",
    )
    delegation_diagnostics: dict[str, Any] = Field(
        default_factory=dict,
        description="Loop diagnostics for delegated execution (depth, repeated edges, break reason)",
    )
    tools_success: bool | None = Field(
        default=None,
        description="Whether tool invocations contributed to a successful outcome",
    )
    delegation_success: bool | None = Field(
        default=None,
        description="Whether delegation(s) contributed to a successful outcome",
    )
    # Clean timing data from llama.cpp (excludes prompt eval overhead)
    prompt_eval_ms: float = Field(default=0.0, description="Prompt evaluation time in ms")
    generation_ms: float = Field(
        default=0.0, description="Token generation time in ms (excludes prompt eval)"
    )
    predicted_tps: float = Field(
        default=0.0, description="Clean generation-only tokens/second from llama.cpp"
    )
    http_overhead_ms: float = Field(
        default=0.0, description="Server-side overhead: HTTP round-trip minus inference time (ms)"
    )
    # Error signaling (Phase 1b): explicit failure codes instead of silent 200 OK
    error_code: int | None = Field(
        default=None,
        description="Error code if request failed (504=timeout, 502=backend down, None=success)",
    )
    error_detail: str | None = Field(
        default=None, description="Structured error description when error_code is set"
    )
    # Orchestrator intelligence diagnostics (for --debug seeding observability)
    cheap_first_attempted: bool = Field(default=False, description="Whether try-cheap-first was attempted")
    cheap_first_passed: bool | None = Field(default=None, description="Whether cheap-first quality gate passed")
    think_harder_attempted: bool = Field(default=False, description="Whether think-harder was attempted before escalation")
    think_harder_succeeded: bool | None = Field(default=None, description="Whether think-harder avoided escalation")
    think_harder_expected_roi: float = Field(default=0.0, description="Estimated per-role ROI for future think-harder attempts")
    grammar_enforced: bool = Field(default=False, description="Whether GBNF grammar was used for constrained generation")
    parallel_tools_used: bool = Field(default=False, description="Whether read-only tools executed in parallel")
    cache_affinity_bonus: float = Field(default=0.0, description="Cache affinity bonus applied during routing")
    cost_dimensions: dict[str, float] = Field(default_factory=dict, description="Multi-dimensional cost breakdown")
    # SkillBank integration
    skills_retrieved: int | None = Field(
        default=0,
        description="Number of skills retrieved from SkillBank (None = SkillBank not loaded)",
    )
    skill_ids: list[str] = Field(default_factory=list, description="IDs of skills used for this request")
    session_persistence: dict[str, Any] = Field(
        default_factory=dict,
        description="Session restore/checkpoint diagnostics for cross-request globals persistence",
    )
    budget_diagnostics: dict[str, Any] = Field(
        default_factory=dict,
        description="Per-request deadline/budget clamp diagnostics (timeout clipping telemetry)",
    )
    # Context window management (C1/C3)
    tool_results_cleared: int = Field(
        default=0, description="Number of stale tool output blocks cleared from context"
    )
    compaction_triggered: bool = Field(
        default=False, description="Whether context compaction was triggered"
    )
    compaction_tokens_saved: int = Field(
        default=0, description="Tokens saved by context compaction"
    )
    # Tool output compression metrics
    compression_metrics: dict[str, Any] = Field(
        default_factory=dict,
        description="Per-turn tool output compression metrics (original/compressed sizes, ratio)",
    )
    # Web research telemetry (Search-R1 reward design)
    web_research_results: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Per-call web_research tool result data (query, sources, timing)",
    )
    # Scratchpad insights (Search-R1 Step 5: session scratchpad memory)
    scratchpad_insights: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Model-extracted semantic insights from session scratchpad (turn, category, insight, confidence)",
    )


class HealthResponse(BaseModel):
    """Response model for health endpoint."""

    status: str = Field(..., description="Health status: ok | degraded")
    models_loaded: int = Field(default=0, description="Number of healthy backends")
    mock_mode_available: bool = Field(default=True, description="Mock mode availability")
    version: str = Field(default="0.1.0", description="API version")
    backend_health: dict[str, Any] | None = Field(
        default=None,
        description="Per-backend circuit breaker status (URL → state/failure_count/cooldown)",
    )
    backend_probes: dict[str, Any] | None = Field(
        default=None,
        description="Per-backend liveness probes (role → {url, ok, latency_ms})",
    )
    knowledge_tools: dict[str, Any] | None = Field(
        default=None,
        description="Knowledge tools availability: {available, tools: {name: {available, error}}}",
    )


class GateResultModel(BaseModel):
    """Model for individual gate result."""

    gate_name: str
    passed: bool
    exit_code: int
    elapsed_seconds: float
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class GatesResponse(BaseModel):
    """Response model for gates endpoint."""

    results: list[GateResultModel]
    all_passed: bool
    total_elapsed_seconds: float


class StatsResponse(BaseModel):
    """Response model for stats endpoint."""

    total_requests: int
    total_turns: int
    average_turns_per_request: float
    mock_requests: int
    real_requests: int
